### ISSUE TITLE
Strip dashes upon entry of phone numbers

### ISSUE THREAD

**Issue by mattstauffer** [mattstauffer/pulledover#13]

**Comment by ejdelmonico** [comment]
Is that striping dashes for ajax submit or through post method on controller.

**Comment by mattstauffer** [comment]
@ejdelmonico Good question. I think in the controller. I've heard that masking things in the input is a recipe for pain, so I think I'd rather avoid it.

**Comment by ejdelmonico** [comment]
Matt,

I’m not sure what you are looking for but I have used something like this helper function before:

/**
-  Replace dash in phone number
  *
- @param $string
  *
- @return mixed
  */
  function strip_dashes($string)
  {
  return str_replace(‘-', '', strtolower($string));
  }

Ed Del Monico
ejdelmonico@gmail.com mailto:ejdelmonico@gmail.com

CONFIDENTIALITY NOTICE:
This e-mail and any attached files from Edward Del Monico may contain information that is privileged, confidential and/or exempt from disclosure under applicable law. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you received this e-mail by accident, please notify the sender immediately and destroy this e-mail and all copies of it. We may scan and or monitor emails sent to and from our servers to ensure regulatory compliance to protect our clients and business.

**Comment by mattstauffer** [comment]
Yep, I would bet that something like that is the ticket. Thanks!

**Comment by RDelorier** [comment]
I just stripped all non numeric characters, same thing right ?

**Comment by mattstauffer** [comment]
@RDelorier yup
