### ISSUE TITLE
Unverified friends receive notification

### ISSUE THREAD

**Issue by RDelorier** [mattstauffer/pulledover#16]
This seems like a good spot for me to jump in and help out ☺

**Comment by RDelorier** [comment]
When a call ends it sends notification text with link to unverified friends.

That should have been in the description...

**Comment by mattstauffer** [comment]
WHOOPS. That's a bug for sure--thanks for reporting!

**Comment by mattstauffer** [comment]
Working on it here:
https://github.com/mattstauffer/pulledover/commit/8e728ec4a5bcc935d3eff3c3541a10af300d32ef
